# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01d7f86f027cfbc7fbb7eb3d7de99cf63ab73b5ce21a7ea918b7651dddf7f6d577db9bdb63a8d8417ea1c9ab6ea77fd7798ae6032a3f15edd6937f0c9b2c021e

test:
  secret_key_base: 7324944533d6218b2d5186b503312d1be099ab64e8e1e1a7f8126b73212e29b67f880cbd8b166e18985cb15777c0fbe4b1e74995d858922141e4e83c1ecd53cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
